name: BTC
favicon: null
layout_spectrum: 0.7249922461342067
typography_spectrum: 0.2938436751719564
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.14778662705793977
  lightness: 0.35155119886621833
  saturation: 0.9866362614557147
  rhythmicContrast: 0.19215638074092567
purpose: []
